### PR TITLE
Improve sre options

### PR DESCRIPTION
**Pull request by zorkow**
This updates the package dependency to the latest SRE so @rbeezer can use Nemeth.

### CODE REVIEW

**Comment by pkra** [comment]
Tests are failing. Can you take a look?

**Comment by zorkow** [comment]
I can't reproduce locally. xml-mapping is no longer required by sre.

**Comment by zorkow** [comment]
Works now. Must have been lingering in beta.0.

**Comment by pkra** [comment]
Thanks!

**Pull request merged**
